// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA01xIMDf-DeEHgk1k6_fXxlpx-6P8ohX0',
    appId: '1:35062421586:web:f84c7dfb6276ebe751678b',
    messagingSenderId: '35062421586',
    projectId: 'catstagram-db47e',
    authDomain: 'catstagram-db47e.firebaseapp.com',
    storageBucket: 'catstagram-db47e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANAXTXnO60IczyYGPJF2m3L9KNpgu6joM',
    appId: '1:35062421586:android:cd9ddc4e40b7db2451678b',
    messagingSenderId: '35062421586',
    projectId: 'catstagram-db47e',
    storageBucket: 'catstagram-db47e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4mwcXl3wBaL9nqivm8UXB-oWx3bv5WHo',
    appId: '1:35062421586:ios:32a7f9e993d2e23351678b',
    messagingSenderId: '35062421586',
    projectId: 'catstagram-db47e',
    storageBucket: 'catstagram-db47e.appspot.com',
    iosClientId: '35062421586-cfcshqv0nk7qgple5bujok891cs2g5m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.catstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4mwcXl3wBaL9nqivm8UXB-oWx3bv5WHo',
    appId: '1:35062421586:ios:32a7f9e993d2e23351678b',
    messagingSenderId: '35062421586',
    projectId: 'catstagram-db47e',
    storageBucket: 'catstagram-db47e.appspot.com',
    iosClientId: '35062421586-cfcshqv0nk7qgple5bujok891cs2g5m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.catstagram',
  );
}
